[package]
name = "broadview-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
axum = "0.7.5"
bson = { version = "2.9.0", features = ["serde_with", "chrono-0_4"] }
chrono = { version = "0.4.35", features = ["serde"] }
dotenv = "0.15.0"
mongodb = { version = "2.8.2", features = ["bson-serde_with"] }
roboat = "0.34.2"
serde = { version = "1.0.197", features = ["derive"] }
serde-bool = "0.1.3"
