name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Deploy
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal

            - name: Build
              run: cargo build --release --locked --verbose

            - name: Create Archive
              run: |
                  mkdir staging

                  cp target/release/broadview-backend staging/
                  cd staging
                  zip ../release.zip *

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: release
                  path: release.zip

            # - name: Set up ssh-agent
            #   uses: webfactory/ssh-agent@v0.5.4
            #   with:
            #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            # - name: Add server to known_hosts
            #   run: echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
            #   env:
            #       KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

            # - name: Deploy Release
            #   run: ./deploy-prod.sh
